# -*- coding: utf-8 -*-
"""mail.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ae5IlVNbI9p-xi_z-WqC4hyS2VRiAxqg
"""

import smtplib
s = smtplib.SMTP('smtp.gmail.com', 587)
s.starttls()

s.login("messiisahot@gmail.com", "anuragp0010")

message = "the code has achieved the accuracy "

s.sendmail("messiisahot@gmail.com", "anuragp0010@kiit.ac.in", message)


    # terminating the session
s.quit()